"""empty message

Revision ID: c91eb2bcf63e
Revises: 0515b6d70dc6
Create Date: 2024-03-19 00:20:01.203091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91eb2bcf63e'
down_revision = '0515b6d70dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key('user_planet_id_fkey', 'planet', ['planet_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('height')

    # ### end Alembic commands ###
